# Generated by Django 5.2.3 on 2025-06-11 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('contact_details', models.TextField(blank=True, null=True)),
                ('account_type', models.CharField(choices=[('customer', 'Customer'), ('vendor', 'Vendor')], max_length=10)),
            ],
        ),
    ]
